version: '3.8'

services:
  db:
    image: mysql:8.0.39
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_db_name
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql-network

volumes:
  db_data:

networks:
  mysql-network:
